# Generated by Django 4.1.5 on 2023-03-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=34)),
                ("stamina", models.SmallIntegerField()),
            ],
            options={
                "db_table": "player",
            },
        ),
        migrations.CreateModel(
            name="TileTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("swamp", "Болото"),
                            ("forest", "Лес"),
                            ("mountains", "Горы"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("tier", models.SmallIntegerField()),
                ("loot_spots", models.IntegerField()),
                ("hidden_loot_spots", models.IntegerField()),
            ],
            options={
                "db_table": "tile_template",
            },
        ),
        migrations.CreateModel(
            name="TileGeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.SmallIntegerField()),
                ("y", models.SmallIntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orm.tiletemplate",
                    ),
                ),
            ],
            options={
                "db_table": "tile_geo",
            },
        ),
    ]
