# Generated by Django 4.1.5 on 2023-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="x",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="y",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
