# Generated by Django 4.1 on 2022-08-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
