# Generated by Django 4.1.5 on 2023-02-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_player_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot_spots', models.IntegerField()),
                ('hidden_loot_spots', models.IntegerField()),
            ],
            options={
                'db_table': 'tiles_info',
            },
        ),
    ]
