# Generated by Django 4.1.5 on 2023-02-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_tilesinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TilesInfo',
            new_name='TileInfo',
        ),
        migrations.AlterModelTable(
            name='tileinfo',
            table='tile_info',
        ),
    ]
